include $(CBUNIT_SOURCE_DIRECTORY)/make.mk
include $(CBUNIT_EXAMPLES_DIRECTORY)/make.mk

CBUNIT_LIBRARY = 							$(CBUNIT_BINARY_DIRECTORY)/cbunit.lib
CBUNIT_EXAMPLES_EXECUTABLE =	$(CBUNIT_BINARY_DIRECTORY)/cbunit-examples

cbunit: $(CBUNIT_LIBRARY)

$(CBUNIT_LIBRARY): $(CBUNIT_OBJECT_FILES)
	$(MAKE_DIRECTORY) $(@D)
	$(MAKE_LIBRARY) $(CBUNIT_LIBRARY) $^

cbunit-clean:
	$(REMOVE) $(CBUNIT_OBJECT_FILES) $(CBUNIT_EXAMPLES_OBJECT_FILES) $(CBUNIT_EXAMPLES_EXECUTABLE) $(CBUNIT_LIBRARY)

cbunit-examples: $(CBUNIT_EXAMPLES_EXECUTABLE)
	$(CBUNIT_EXAMPLES_EXECUTABLE) --reporter spec --output ansi256

$(CBUNIT_EXAMPLES_EXECUTABLE): $(CBUNIT_OBJECT_FILES) $(CBUNIT_EXAMPLES_OBJECT_FILES) examples/main.cpp
	$(MAKE_DIRECTORY) $(@D)
	$(REMOVE) $@
	$(CPP) -o $@ $^ -I$(CBUNIT_INCLUDE_DIRECTORY)

$(CBUNIT_BUILD_DIRECTORY)/%.o: $(CBUNIT_SOURCE_DIRECTORY)/%.cpp
	$(MAKE_DIRECTORY) $(@D)
	$(CPP) -c -o $@ $^ -I$(CBUNIT_INCLUDE_DIRECTORY)

$(CBUNIT_BUILD_DIRECTORY)/examples/%.o: $(CBUNIT_EXAMPLES_DIRECTORY)/%.cpp
	$(MAKE_DIRECTORY) $(@D)
	$(CPP) -c -o $@ $^ -I$(CBUNIT_INCLUDE_DIRECTORY)

.PHONY: cbunit-clean