#pragma once
#include "ExpectBoolean.hpp"
#include "ExpectInteger.hpp"
#include "ExpectFloatingPoint.hpp"
#include "ExpectString.hpp"
#include "ExpectCString.hpp"
#include "ExpectPointer.hpp"
#include "ExpectSequence.hpp"
#include "ExpectSame.hpp"