CBUNIT_SOURCE_DIRECTORY = src
CBUNIT_INCLUDE_DIRECTORY = include
CBUNIT_BUILD_DIRECTORY = build
CBUNIT_BINARY_DIRECTORY = bin
CBUNIT_EXAMPLES_DIRECTORY = examples

CBUNIT_SOURCE_FILES =
CBUNIT_EXAMPLES_FILES =

CBUNIT_OBJECT_FILES = $(patsubst $(CBUNIT_SOURCE_DIRECTORY)/%.cpp, $(CBUNIT_BUILD_DIRECTORY)/%.o, $(CBUNIT_SOURCE_FILES))

CBUNIT_EXAMPLES_OBJECT_FILES = $(patsubst $(CBUNIT_EXAMPLES_DIRECTORY)/%.cpp, $(CBUNIT_BUILD_DIRECTORY)/examples/%.o, $(CBUNIT_EXAMPLES_FILES))